# Generated by Django 4.0.5 on 2022-07-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_desc_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(default='exit', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
