# Generated by Django 4.0.5 on 2022-09-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_postforher_options_alter_postforhim_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostForHim',
            new_name='Post',
        ),
        migrations.DeleteModel(
            name='PostForHer',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
